---
abstract: 'Seamless DB schema up- and downgrades'
author:
  - 'Sebastian Riedel, C<sri@oook.de>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Migration
provides:
  DBIx::Migration:
    file: lib/DBIx/Migration.pm
    version: '0.09'
requires:
  DBD::SQLite: '0'
  DBI: '0'
  File::Slurp: '0'
  File::Spec: '0'
  Moose: '0'
  Syntax::Keyword::Try: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.09'
