jobs:
  test:
    parameters:
      perl-version:
        description: The Perl version we want to test with
        type: string
        default: "5.34"
    docker:
      - image: perldocker/perl-tester:<< parameters.perl-version >>
    steps:
      - checkout
      - run:
          name: pre_install
          command: |
            cpm install --no-test
            --mirror=http://cpan.cpantesters.org/ Test::Requires::Git Devel::Cover::Report::Codecov

      - run:
          name: Install dist deps
          command: |
            cpanm -n --installdeps .
      - run:
          name: Run Tests
          command: |
            perl Makefile.PL && make build && make test
      - run:
          name: after_success
          command: |
            cover -test -report codecov

workflows:
  build-workflow:
    jobs: &1
    - test:
        matrix:
          parameters:
            perl-version:
              - "5.24"
              - "5.26"
              - "5.28"
              - "5.30"
              - "5.32"
              - "5.34"
version: 2.1
